.NONPOSIX:

PREFIX = /usr
ICONPREFIX = $(PREFIX)/share/icons

SIZES = 8 16 22 24 32 48

DIRS =\
	actions\
	apps\
	categories\
	devices\
	emblems\
	emotes\
	mimetypes\
	places\
	status

ICONS =\
	categories/preferences-desktop\
		categories/gnome-control-center\
			categories/kcontrol\
		categories/gnome-settings\
			categories/xfce4-settings\
		categories/gtk-preferences\
		categories/redhat-preferences\
		apps/dconf-editor\
	categories/applications-internet\
		categories/gnome-globe\
		categories/package_network\
		categories/redhat-internet\
		categories/stock_internet\
	categories/applications-development\
		categories/gnome-devel\
		categories/package_development\
		categories/redhat-programming\
	categories/applications-system\
		categories/gnome-system\
		categories/package_system\
		categories/redhat-system_tools\
	categories/applications-graphics\
		categories/gnome-graphics\
		categories/package_graphics\
		categories/redhat-graphics\
		categories/xfce-graphics\
	categories/applications-games\
		categories/gnome-joystick\
		categories/packages_games\
		categories/redhat-games\
		categories/xfce-games\
		devices/input-gaming\
			devices/joystick\
			devices/yast_joystick\
	categories/preferences-system\
		categories/package_settings\
		categories/redhat-system_settings\
		categories/xfce-system-settings\
		categories/administration\
	categories/preferences-other\
		categories/applications-other\
			categories/gnome-other\
	categories/applications-multimedia\
		categories/gnome-multimedia\
		categories/package_multimedia\
		categories/redhat-sound_video\
		categories/xfce-multimedia\
	categories/applications-engineering\
	categories/applications-utilities\
		categories/applications-accessories\
			categories/gnome-util\
			categories/package_utilities\
			categories/redhat-accessories\
			categories/xfce-utils\
	categories/system-help\
	categories/applications-science\
	categories/preferences-desktop-personal\
	categories/preferences-system-network\
	categories/applications-office\
		categories/gnome-applications\
		categories/package_office\
		categories/redhat-office\
		categories/xfce-office\
	apps/brasero\
		actions/brasero-disc-100\
		apps/isomaster\
		apps/grip\
	apps/mail-client\
		apps/claws-mail\
			apps/claws-mail_logo\
	apps/ufraw\
	apps/gnome-gnibbles\
	apps/preferences-desktop-theme\
		apps/style\
		apps/gnome-settings-theme\
		mimetypes/application-x-theme\
	apps/preferences-desktop-keyboard\
		apps/system-config-keyboard\
	apps/wireshark\
	apps/nuvolaplayer\
	apps/pacman\
	apps/mplayer\
	apps/audacity\
		apps/gnome-mime-application-x-audacity-project\
	apps/emu-snes\
		apps/zsnes\
	apps/emu-nes\
		apps/fceux\
	apps/citrix\
	apps/preferences-desktop-accessibility\
		apps/access\
		apps/accessibility-directory\
		apps/gnome-settings-accessibility-technologies\
	apps/preferences-desktop-locale\
		apps/config-language\
		apps/locale\
	apps/power-manager\
		apps/gnome-power-manager\
	apps/accessories-calculator\
		apps/gnome-calculator\
	apps/preferences-color\
		apps/colors\
		apps/kipi\
		apps/gpick\
		apps/gnome-color-browser\
			apps/gnome-color-chooser\
		apps/mate-color-select\
		actions/fill-color\
			actions/color-line\
			actions/format-fill-color\
	apps/help-faq\
		actions/help-faq\
	apps/bluetooth\
		apps/preferences-system-bluetooth\
	apps/accessories-character-map\
		apps/gnome-character-map\
		apps/gucharmap\
		apps/kcharselect\
	apps/multimedia-volume-control\
		apps/arts\
		apps/gnome-mixer\
		apps/kcmsound\
		apps/multimedia\
		apps/volume-knob\
		apps/xfce4-mixer\
	apps/accessories-dictionary\
	apps/utilities-system-monitor\
		apps/gnome-monitor\
		apps/ksysguard\
		apps/htop\
		apps/utilities_system_monitor\
	apps/mate-panel-launcher\
		apps/gnome-panel-launcher\
	apps/system-software-install\
	apps/system-software-update\
		apps/update-manager\
		apps/zen-icon\
	apps/utilities-terminal\
		apps/utilities_terminal\
		apps/xterm\
		apps/xterm-color\
		apps/uxterm\
		apps/terminator\
		apps/gnome-terminal\
			apps/gnome-term\
		apps/konsole\
		apps/openterm\
		apps/terminal\
		apps/xfce-terminal\
	apps/preferences-system-windows\
		apps/xfwm4\
		apps/gnome-window-manager\
		apps/kcmkwm\
		apps/kwin\
	apps/system-file-manager\
		apps/file-manager\
		apps/redhat-filemanager\
		apps/xfce-filemanager\
		apps/kfm\
		apps/caja\
		apps/thunar\
	apps/preferences-system-search\
	apps/preferences-desktop-default-applications\
	apps/applets-screenshooter\
	apps/user-info\
	apps/steam\
	apps/python\
		mimetypes/application-x-python-bytecode\
			mimetypes/gnome-mime-application-x-python-bytecode\
	apps/kega-fusion\
	apps/dosbox\
		mimetypes/application-x-ms-dos-executable\
	apps/system-users\
		apps/config-users\
		apps/kuser\
		apps/system-config-users\
	apps/preferences-desktop-screensaver\
		apps/kscreensaver\
		apps/screensaver\
		apps/xscreensaver\
	apps/preferences-system-time\
		apps/mate-panel-clock\
			apps/gnome-panel-clock\
	apps/preferences-system-notifications\
		apps/mate-notification-properties\
	apps/preferences-desktop-remote-desktop\
		apps/gnome-remote-desktop\
		apps/krfb\
	apps/preferences-system-sharing\
	apps/preferences-system-network-proxy\
		apps/mate-network-properties\
	apps/preferences-system-network\
	apps/preferences-system-details\
	apps/preferences-system-devices\
	apps/preferences-desktop-wallpaper\
		apps/background\
		apps/gnome-settings-background\
		apps/wallpaper\
		apps/xfce4-backdrop\
	apps/google-chrome\
		apps/google-chrome-stable\
		apps/chromium\
	apps/firefox\
		apps/mozilla-firefox\
	apps/abiword\
		apps/abiword_48\
	apps/meld\
	apps/mate\
	apps/pidgin\
	apps/preferences-desktop-font\
		apps/fonts\
		apps/gnome-settings-font\
	apps/gnome\
		places/gnome-main-menu\
	apps/linux\
		places/distributor-logo\
			places/novell-button\
			places/start-here\
		mimetypes/vmlinuz\
	apps/baobab\
	apps/gnome-disks\
	apps/gnome-disks-state-standby\
	apps/mate-panel\
		apps/gnome-panel\
	apps/mate-panel-window-list\
		apps/gnome-panel-window-list\
	apps/mate-panel-window-menu\
		apps/gnome-panel-window-menu\
	apps/mate-panel-workspace-switcher\
		apps/gnome-panel-workspace-switcher\
		apps/gnome-workspaces\
		apps/xfce4-workspaces\
	apps/mate-panel-separator\
		apps/gnome-panel-separator\
	apps/mate-panel-notification-area\
		apps/gnome-panel-notification-area\
	apps/dooble\
		apps/dooble-qt4\
	apps/vlc\
		apps/vlc-xmas\
	apps/kdenlive\
		mimetypes/application-x-kdenlive\
		mimetypes/application-x-kdenlivetitle\
	apps/mpv\
	apps/cups\
	apps/deluge\
	apps/gimp\
		mimetypes/image-x-xcf\
			mimetypes/image-x-compressed-xcf\
			mimetypes/image-x-psd\
	apps/inkscape\
	apps/utilities-file-archiver\
		apps/utilities-archiver\
		apps/utilities_file_archiver\
		apps/file-roller\
		apps/engrampa\
		apps/p7zip\
	apps/eom\
		apps/eog\
			apps/gnome-eog\
	apps/xmonad\
	apps/emacs\
		apps/emacs23\
	apps/flash-player-properties\
		apps/flash\
		mimetypes/application-x-flash-video\
	apps/steam\
	apps/goa-panel\
	apps/qv4l2\
	apps/blender\
		mimetypes/application-x-blender\
	apps/preferences-system-privacy\
	apps/preferences-desktop-keyboard-shortcuts\
		apps/gnome-settings-keybindings\
		apps/key_bindings\
	apps/help-contents\
		actions/help-contents\
			actions/help\
			actions/gtk-help\
			actions/stock_help\
	apps/web-browser\
	apps/classic_invaders\
	apps/accessories-text-editor\
		apps/kedit\
		apps/text-editor\
		apps/gedit\
			apps/gedit-logo\
			apps/gedit-icon\
	apps/help-browser\
		apps/gnome-help\
		apps/khelpcenter\
		apps/susehelpcenter\
	apps/mate-typing-monitor\
	apps/phonon-gstreamer\
	apps/preferences-desktop-display\
		apps/mate-preferences-desktop-display\
		apps/msd-xrandr\
	apps/force-exit\
		apps/mate-panel-force-quit\
			apps/gnome-panel-force-quit\
	apps/mate-panel-fish\
		apps/gnome-panel-fish\
	apps/mate-panel-drawer\
		apps/gnome-panel-drawer\
	status/mail-read\
		status/stock_mail-open\
	status/mail-replied\
		status/stock_mail-replied\
	status/mail-replied-rtl\
		status/stock_mail-replied-rtl\
	status/mail-signed\
	status/mail-signed-verified\
	status/mail-unread\
		status/stock_mail-unread\
	status/content-loading\
		status/image-loading\
			status/gnome-fs-loading-icon\
	status/airplane-mode\
	status/alarm\
		apps/alarm\
			apps/alarm-clock\
			apps/alarm-timer\
	status/appointment-missed\
		status/stock_appointment-reminder-excl\
	status/appointment-soon\
		status/stock_appointment-reminder\
	status/audio-volume-high\
		status/stock_volume-max\
		status/stock_volume\
	status/audio-volume-low\
		status/stock_volume-0\
		status/stock_volume-min\
	status/audio-volume-medium\
		status/stock_volume-med\
	status/audio-volume-muted\
		status/stock_volume-mute\
	status/avatar-default\
	status/battery-caution-charging\
	status/battery-caution\
	status/battery-empty-charging\
	status/battery-empty\
	status/battery-full-charged\
	status/battery-full-charging\
	status/battery-full\
	status/battery-good-charging\
	status/battery-good\
	status/battery-low-charging\
	status/battery-low\
	status/battery-missing\
	status/bluetooth-active\
	status/bluetooth-disabled\
	status/call-missed\
	status/changes-allow\
	status/changes-prevent\
	status/channel-insecure\
	status/channel-secure\
	status/checkbox-checked\
	status/checkbox-mixed\
	status/checkbox\
	status/computer-fail\
	status/user-available\
	status/user-away\
	status/user-busy\
	status/user-idle\
	status/user-invisible\
	status/user-offline\
	status/user-status-pending\
	status/terminal-bell\
	status/folder-open\
		status/folder_open\
		status/stock_open\
	status/folder-drag-accept\
		status/gnome-fs-directory-accept\
	status/folder-visiting\
		status/gnome-fs-directory-visiting\
	status/dialog-warning\
		status/gtk-dialog-warning\
		status/important\
		status/messagebox_warning\
		status/stock_dialog-warning\
	status/dialog-error\
		status/error\
		status/gtk-dialog-error\
		status/messagebox_critical\
		status/stock_dialog-error\
	status/dialog-question\
		status/gtk-dialog-question\
		status/stock_dialog-question\
	status/dialog-information\
		status/gtk-dialog-info\
		status/stock_dialog-info\
		status/messagebox_info\
		status/info\
	status/dialog-password\
		status/gtk-dialog-authentication\
	status/display-brightness\
	status/keyboard-brightness\
	status/user-trash-full\
		status/edittrash\
		status/gnome-fs-trash-full\
		status/gnome-stock-trash-full\
		status/stock_trash_full\
		status/trashcan_full\
		status/xfce-trash_full\
	status/network-error\
		status/gnome-netstatus-error\
	status/network-offline\
		status/connect_no\
		status/gnome-netstatus-disconn\
		status/nm-no-connection\
	status/network-idle\
		status/gnome-netstatus-idle\
	status/network-receive\
		status/gnome-netstatus-rx\
	status/network-transmit\
		status/gnome-netstatus-tx\
	status/network-transmit-receive\
		status/gnome-netstatus-txrx\
	status/network-no-route\
	status/network-wired\
		status/connect_established\
		status/nm-device-wired\
	status/network-wired-acquiring\
		status/connect_creating\
	status/network-wired-no-route\
	status/network-wired-disconnected\
	status/network-wired-offline\
	status/network-wireless-acquiring\
	status/network-wireless-connected\
		status/nm-adhoc\
	status/network-wireless-hotspot\
	status/network-wireless-no-route\
	status/network-wireless-offline\
	status/network-wireless-signal-excellent\
		status/nm-device-wireless\
	status/network-wireless-signal-good\
	status/network-wireless-signal-none\
	status/network-wireless-signal-ok\
	status/network-wireless-signal-weak\
	status/network-wireless-encrypted\
		status/gnome-dev-wavelan-encrypted\
	status/mail-attachment\
		status/stock_attach\
	status/media-playlist-consecutive-rtl\
	status/media-playlist-consecutive\
	status/media-playlist-repeat-rtl\
	status/media-playlist-repeat-song-rtl\
	status/media-playlist-repeat-song\
	status/media-playlist-repeat\
		status/stock_repeat\
	status/media-playlist-shuffle-rtl\
	status/media-playlist-shuffle\
		status/stock_shuffle\
	status/microphone-sensitivity-high\
	status/microphone-sensitivity-low\
	status/microphone-sensitivity-medium\
	status/microphone-sensitivity-muted\
	status/network-cellular-3g\
	status/network-cellular-4g\
	status/network-cellular-acquiring\
	status/network-cellular-connected\
	status/network-cellular-edge\
	status/network-cellular-gprs\
	status/network-cellular-hspa\
	status/network-cellular-no-route\
	status/network-cellular-offline\
	status/network-cellular-signal-excellent\
	status/network-cellular-signal-good\
	status/network-cellular-signal-none\
	status/network-cellular-signal-ok\
	status/network-cellular-signal-weak\
	status/network-cellular-umts\
	status/network-vpn-acquiring\
	status/network-vpn\
		devices/network-vpn\
	status/non-starred\
	status/printer-error\
	status/printer-printing\
	status/printer-warning\
	status/radio-checked\
	status/radio-mixed\
	status/radio\
	status/rotation-allowed\
	status/rotation-locked\
	status/security-high\
		status/stock_lock-ok\
	status/security-low\
		status/stock_lock-broken\
		status/stock_lock-open\
	status/security-medium\
		status/stock_lock\
	status/semi-starred-rtl\
	status/semi-starred\
	status/software-update-available\
	status/software-update-urgent\
	status/starred\
	status/system-lock-screen\
	status/task-due\
	status/task-past-due\
	status/touchpad-disabled\
	status/view-wrapped-rtl\
	status/view-wrapped\
	status/weather-overcast\
		status/stock_weather-cloudy\
	status/weather-showers\
		status/stock_weather-showers\
	status/weather-showers-scattered\
	status/weather-snow\
		status/stock_weather-snow\
	status/weather-storm\
		status/stock_weather-storm\
	status/weather-fog\
		status/stock_weather-fog\
	status/weather-severe-alert\
	status/weather-clear\
		status/stock_weather-sunny\
		status/sunny\
	status/weather-few-clouds\
		status/stock_weather-few-clouds\
	status/weather-clear-night-000\
	status/weather-clear-night-010\
	status/weather-clear-night-020\
	status/weather-clear-night-030\
	status/weather-clear-night-040\
	status/weather-clear-night-050\
	status/weather-clear-night-060\
	status/weather-clear-night-070\
	status/weather-clear-night-080\
	status/weather-clear-night-090\
	status/weather-clear-night-100\
	status/weather-clear-night-110\
	status/weather-clear-night-120\
	status/weather-clear-night-130\
	status/weather-clear-night-140\
	status/weather-clear-night-150\
	status/weather-clear-night-160\
	status/weather-clear-night-170\
	status/weather-clear-night-180\
		status/weather-clear-night\
			status/stock_weather-night-clear\
	status/weather-clear-night-190\
	status/weather-clear-night-200\
	status/weather-clear-night-210\
	status/weather-clear-night-220\
	status/weather-clear-night-230\
	status/weather-clear-night-240\
	status/weather-clear-night-250\
	status/weather-clear-night-260\
	status/weather-clear-night-270\
	status/weather-clear-night-280\
	status/weather-clear-night-290\
	status/weather-clear-night-300\
	status/weather-clear-night-310\
	status/weather-clear-night-320\
	status/weather-clear-night-330\
	status/weather-clear-night-340\
	status/weather-clear-night-350\
	status/weather-few-clouds-night-000\
	status/weather-few-clouds-night-010\
	status/weather-few-clouds-night-020\
	status/weather-few-clouds-night-030\
	status/weather-few-clouds-night-040\
	status/weather-few-clouds-night-050\
	status/weather-few-clouds-night-060\
	status/weather-few-clouds-night-070\
	status/weather-few-clouds-night-080\
	status/weather-few-clouds-night-090\
	status/weather-few-clouds-night-100\
	status/weather-few-clouds-night-110\
	status/weather-few-clouds-night-120\
	status/weather-few-clouds-night-130\
	status/weather-few-clouds-night-140\
	status/weather-few-clouds-night-150\
	status/weather-few-clouds-night-160\
	status/weather-few-clouds-night-170\
	status/weather-few-clouds-night-180\
		status/weather-few-clouds-night\
			status/stock_weather-night-few-clouds\
	status/weather-few-clouds-night-190\
	status/weather-few-clouds-night-200\
	status/weather-few-clouds-night-210\
	status/weather-few-clouds-night-220\
	status/weather-few-clouds-night-230\
	status/weather-few-clouds-night-240\
	status/weather-few-clouds-night-250\
	status/weather-few-clouds-night-260\
	status/weather-few-clouds-night-270\
	status/weather-few-clouds-night-280\
	status/weather-few-clouds-night-290\
	status/weather-few-clouds-night-300\
	status/weather-few-clouds-night-310\
	status/weather-few-clouds-night-320\
	status/weather-few-clouds-night-330\
	status/weather-few-clouds-night-340\
	status/weather-few-clouds-night-350\
	status/weather-windy\
	status/user-not-tracked\
	status/thunderbolt-acquiring\
	status/night-light\
	status/daytime-sunrise\
	status/daytime-sunset\
	status/orientation-landscape\
	status/orientation-landscape-inverse\
	status/orientation-portrait\
	status/orientation-portrait-inverse\
	status/image-missing\
		status/gtk-missing-image\
	actions/info\
	actions/insert-horizontal-rule\
	actions/jockey-disabled\
	actions/jockey-enabled\
	actions/mail-copy\
	actions/mail-move\
	actions/mail-mark-read\
	actions/mail-inbox\
	actions/mail-outbox\
	actions/webcamreceive\
	actions/webcamsend\
	actions/media-optical-blank\
	actions/brasero-disc-00\
	actions/brasero-disc-05\
	actions/brasero-disc-10\
	actions/brasero-disc-15\
	actions/brasero-disc-20\
	actions/brasero-disc-25\
	actions/brasero-disc-30\
	actions/brasero-disc-35\
	actions/brasero-disc-40\
	actions/brasero-disc-45\
	actions/brasero-disc-50\
	actions/brasero-disc-55\
	actions/brasero-disc-60\
	actions/brasero-disc-65\
	actions/brasero-disc-70\
	actions/brasero-disc-75\
	actions/brasero-disc-80\
	actions/brasero-disc-85\
	actions/brasero-disc-90\
	actions/brasero-disc-95\
	actions/terminator_active_broadcast_all\
	actions/terminator_active_broadcast_group\
	actions/terminator_active_broadcast_off\
	actions/terminator_receive_off\
	actions/terminator_receive_on\
	actions/align-horizontal-center\
	actions/align-horizontal-left\
	actions/align-horizontal-left-out\
	actions/align-horizontal-right\
	actions/align-horizontal-right-out\
	actions/align-vertical-bottom\
	actions/align-vertical-bottom-out\
	actions/align-vertical-center\
	actions/align-vertical-top\
	actions/align-vertical-top-out\
	actions/format-connect-node\
	actions/format-disconnect-node\
	actions/go-first-view-page\
	actions/go-last-view-page\
	actions/go-next-view-page\
	actions/go-previous-view-page\
	actions/add-files-to-archive\
	actions/add-folder-to-archive\
	actions/gtk-dnd\
	actions/mail-forward\
		actions/gnome-stock-mail-fwd\
		actions/mail_forward\
		actions/stock_mail-forward\
	actions/mail-forward-rtl\
		actions/gnome-stock-mail-fwd-rtl\
		actions/mail_forward-rtl\
		actions/stock_mail-forward-rtl\
	actions/mail-reply-all\
		actions/mail_replyall\
		actions/stock_mail-reply-to-all\
	actions/mail-reply-all-rtl\
		actions/mail_replyall-rtl\
		actions/stock_mail-reply-to-all-rtl\
	actions/mail-reply-list\
	actions/mail-reply-list-rtl\
	actions/mail-reply-sender\
		actions/gnome-stock-mail-rpl\
		actions/mail_reply\
		actions/stock_mail-reply\
	actions/mail-reply-sender-rtl\
		actions/gnome-stock-mail-rpl-rtl\
		actions/mail_reply-rtl\
		actions/stock_mail-reply-rtl\
	actions/document-export\
	actions/document-import\
	actions/extract-archive\
	actions/mail-send\
		actions/gnome-stock-mail-snd\
		actions/mail_send\
		actions/stock_mail-send\
	actions/mail-send-receive\
		actions/stock_mail-send-receive\
	actions/mail-mark-important\
	actions/calibrate\
	actions/edit-bomb\
	actions/edit-rename\
	actions/object-crop\
	actions/view-calendar-day\
	actions/view-calendar-list\
	actions/view-calendar-week\
	actions/view-calendar-workweek\
	actions/view-coverflow\
	actions/view-treemap\
	actions/view-ringschart\
	actions/view-list-column\
	actions/view-list-filter\
	actions/view-list-tree\
	actions/view-left-close\
	actions/view-left-new\
	actions/view-right-close\
	actions/view-right-new\
	actions/view-above-close\
		actions/view-up-close\
	actions/view-above-new\
		actions/view-up-new\
	actions/view-below-close\
		actions/view-down-close\
	actions/view-below-new\
		actions/view-down-new\
	actions/action-unavailable\
	actions/call-end\
		actions/call-stop\
	actions/call-start\
	actions/color-select\
	actions/document-open-recent\
		actions/view-history\
	actions/document-print-preview\
		actions/filequickprint\
		actions/gtk-print-preview\
		actions/stock_print-preview\
	actions/document-print\
		actions/fileprint\
		actions/gtk-print\
		actions/stock_print\
	actions/document-properties\
		actions/gtk-properties\
		actions/stock_file-properites\
		actions/stock_properties\
	actions/document-revert\
		actions/gtk-revert-to-saved-ltr\
		actions/gtk-revert-to-saved-rtl\
		actions/revert\
	actions/document-revert-rtl\
	actions/document-save-as\
		actions/filesaveas\
		actions/gtk-save-as\
		actions/stock_save-as\
	actions/document-save\
		actions/filesave\
		actions/gtk-save\
		actions/stock_save\
	actions/selection-end\
	actions/selection-end-rtl\
	actions/selection-start\
	actions/selection-start-rtl\
	actions/appointment-new\
		actions/appointment\
		actions/stock_new-appointment\
	actions/bookmark-add\
		actions/bookmark_add\
		actions/bookmark-new\
		actions/bookmarks_list_add\
		actions/stock_add-bookmark\
		actions/stock_help-add-bookmark\
	actions/edit-cut\
		actions/editcut\
		actions/gtk-cut\
		actions/stock_cut\
	actions/edit-delete\
		actions/editdelete\
		actions/gtk-delete\
		actions/stock_delete\
	actions/edit-find\
		actions/filefind\
		actions/find\
		actions/gtk-find\
		actions/stock_search\
		actions/system-search\
			actions/kfind\
			actions/gnome-searchtool\
			actions/search\
	actions/edit-find-replace\
		actions/gtk-find-and-replace\
		actions/stock_search-and-replace\
	actions/edit-paste\
		actions/editpaste\
		actions/gtk-paste\
		actions/stock_paste\
	actions/tab-new\
		actions/stock_new-tab\
		actions/tab_new\
	actions/tab-close\
	actions/format-text-bold\
		actions/gtk-bold\
		actions/stock_text_bold\
		actions/text_bold\
	actions/document-edit\
		actions/gtk-edit\
	actions/format-text-direction-ltr\
	actions/format-text-direction-rtl\
	actions/format-text-italic\
		actions/gtk-italic\
		actions/stock_text_italic\
		actions/text_italic\
	actions/format-text-strikethrough\
		actions/gtk-strikethrough\
		actions/stock_text-strikethrough\
		actions/text_strike\
	actions/format-text-underline\
		actions/gtk-underline\
		actions/stock_text_underlined\
		actions/text_under\
	actions/tools-check-spelling\
		actions/stock_spellcheck\
		actions/gtk-spell-check\
	actions/system-run\
		actions/gnome-run\
		actions/gtk-execute\
	actions/edit-undo\
		actions/edit-redo-rtl\
		actions/gtk-undo-ltr\
		actions/stock_undo\
		actions/undo\
	actions/edit-redo\
		actions/edit-undo-rtl\
		actions/gtk-redo-ltr\
		actions/redo\
		actions/stock_redo\
	actions/application-exit\
		actions/exit\
		actions/gtk-quit\
		actions/xfce-system-exit\
	actions/contact-new\
		actions/stock_new-bcard\
		actions/user-new\
	actions/contact-delete\
		actions/user-delete\
			actions/list-remove-user\
	actions/user-group-new\
	actions/user-group-delete\
	actions/drive-multidisk\
	actions/focus-legacy-systray\
	actions/focus-top-bar\
	actions/focus-windows\
	actions/font-select\
	actions/image-crop\
	actions/image-denoise\
	actions/image-filter\
	actions/insert-image\
	actions/insert-link\
	actions/insert-object\
	actions/insert-text\
	actions/list-remove-all\
	actions/process-stop\
		actions/gtk-cancel\
		actions/gtk-stop\
		actions/stock_stop\
		actions/stop\
	actions/object-flip-horizontal\
	actions/object-flip-vertical\
	actions/object-rotate-left\
	actions/object-rotate-right\
	actions/object-select\
	actions/open-menu\
	actions/pan-down\
	actions/pan-end\
		actions/pan-start-rtl\
	actions/pan-start\
		actions/pan-end-rtl\
	actions/pan-up\
	actions/view-continuous\
		actions/view-page-continuous\
	actions/view-dual\
		actions/view-page-facing\
	actions/view-fullscreen\
		actions/gtk-fullscreen\
		actions/stock_fullscreen\
		actions/window_fullscreen\
	actions/view-mirror\
	actions/view-pin\
	actions/view-grid\
		actions/view-list-icons\
	actions/view-list\
		actions/view-list-details\
	actions/view-more\
	actions/view-paged\
	actions/view-restore\
		actions/gtk-leave-fullscreen\
		actions/stock_leave-fullscreen\
		actions/window_nofullscreen\
	actions/view-sort-ascending\
		actions/gtk-sort-ascending\
	actions/view-sort-descending\
		actions/gtk-sort-descending\
	actions/view-split-left-right\
		actions/view-split-vertically\
		actions/terminator_vert\
	actions/view-split-top-bottom\
		actions/view-split-horizontally\
		actions/terminator_horiz\
	actions/window-close\
		actions/gtk-close\
		actions/stock_close\
		actions/dialog-no\
			actions/gtk-no\
	actions/dialog-apply\
		actions/gtk-apply\
		actions/stock_calc-accept\
		actions/stock_mail-filters-apply\
		actions/dialog-yes\
			actions/stock_yes\
			actions/gtk-yes\
		actions/dialog-ok\
			actions/gtk-ok\
			actions/ok\
		actions/dialog-ok-apply\
		actions/games-endturn\
		actions/stock_mark\
	actions/window-maximize\
	actions/window-minimize\
	actions/window-restore\
	actions/zoom-fit-best\
		actions/gtk-zoom-fit\
		actions/zoom-fit-page\
			actions/stock_zoom-page\
		actions/viewmagfit\
		actions/zoom-best-fit\
	actions/zoom-in\
		actions/gtk-zoom-in\
		actions/stock_zoom-in\
		actions/viewmag+\
	actions/zoom-original\
		actions/gtk-zoom-100\
		actions/stock_zoom-1\
		actions/viewmag1\
	actions/zoom-out\
		actions/gtk-zoom-out\
		actions/stock_zoom-out\
		actions/viewmag-\
	actions/zoom-fit-width\
	actions/zoom-fit-height\
	actions/help-about\
		actions/gtk-about\
		actions/stock_about\
	actions/content-loading\
	actions/document-new\
		actions/filenew\
		actions/gtk-new\
		actions/stock_new-text\
	actions/document-open\
		actions/fileopen\
		actions/gtk-open\
	actions/document-page-setup\
		actions/stock_print-setup\
	actions/edit-clear-all\
		actions/editclear\
		actions/gtk-clear\
		actions/edit-clear\
	actions/edit-clear-all-rtl\
		actions/edit-clear-rtl\
	actions/edit-clear-before\
		actions/edit-clear-after-rtl\
	actions/edit-clear-after\
		actions/edit-clear-before-rtl\
	actions/edit-copy\
		actions/editcopy\
		actions/gtk-copy\
		actions/stock_copy\
	actions/edit-select-all\
		actions/gtk-select-all\
		actions/stock_select-all\
	actions/edit-select\
	actions/find-location\
	actions/window-new\
		actions/window_new\
		actions/stock_new-window\
	actions/folder-new\
		actions/folder_new\
		actions/stock_new-dir\
	actions/format-indent-less\
		actions/format-indent-more-rtl\
		actions/gnome-stock-text-unindent\
		actions/gtk-indent-rtl\
		actions/gtk-unindent-ltr\
		actions/stock_text_unindent\
	actions/format-indent-more\
		actions/format-indent-less-rtl\
		actions/gnome-stock-text-indent\
		actions/gtk-indent-ltr\
		actions/gtk-unindent-rtl\
		actions/stock_text_indent\
	actions/format-justify-center\
		actions/centrejust\
		actions/gtk-justify-center\
		actions/stock_text_center\
	actions/format-justify-fill\
		actions/gtk-justify-fill\
		actions/stock_text_justify\
	actions/format-justify-left\
		actions/gtk-justify-left\
		actions/leftjust\
		actions/stock_text_left\
	actions/format-justify-right\
		actions/gtk-justify-right\
		actions/rightjust\
		actions/stock_text_right\
	actions/go-home\
		actions/gohome\
		actions/gtk-home\
		actions/kfm_home\
		actions/redhat-home\
		actions/stock_home\
	actions/go-jump-rtl\
		actions/gtk-jump-to-rtl\
	actions/go-jump\
		actions/gtk-jump-to-ltr\
	actions/image-sharpen\
	actions/list-add\
		actions/add\
		actions/gtk-add\
	actions/list-remove\
		actions/gtk-remove\
		actions/remove\
	actions/mark-location\
		apps/google-local\
	actions/media-eject\
		actions/player_eject\
	actions/media-playback-pause\
		actions/gtk-media-pause\
		actions/player_pause\
		actions/stock_media-pause\
	actions/media-playback-start-rtl\
	actions/media-playback-start\
		actions/gtk-media-play-ltr\
		actions/player_play\
		actions/stock_media-play\
	actions/media-playback-stop\
		actions/gtk-media-stop\
		actions/player_stop\
		actions/stock_media-stop\
	actions/media-record\
		actions/gtk-media-record\
		actions/player_record\
		actions/stock_media-rec\
	actions/media-seek-backward\
		actions/gtk-media-forward-rtl\
		actions/gtk-media-rewind-ltr\
		actions/media-seek-foreward-rtl\
		actions/player_rew\
		actions/stock_media-rew\
	actions/media-seek-forward\
		actions/gtk-media-forward-ltr\
		actions/gtk-media-rewind-rtl\
		actions/media-seek-backward-rtl\
		actions/player_fwd\
		actions/stock_media-fwd\
	actions/media-skip-backward\
		actions/gtk-media-next-rtl\
		actions/gtk-media-previous-ltr\
		actions/media-skip-foreward-rtl\
		actions/player_start\
		actions/stock_media-prev\
	actions/media-skip-forward\
		actions/gtk-media-next-ltr\
		actions/gtk-media-previous-rtl\
		actions/media-skip-backward-rtl\
		actions/player_end\
		actions/stock_media-next\
	actions/media-view-subtitles\
	actions/address-book-new\
		actions/stock_new-address-book\
	actions/star-new\
	actions/view-refresh\
		actions/gtk-refresh\
		actions/reload3\
		actions/reload_all_tabs\
		actions/reload_page\
		actions/reload\
		actions/stock_refresh\
	actions/go-bottom\
		actions/bottom\
		actions/gtk-goto-bottom\
		actions/stock_bottom\
	actions/go-down\
		actions/down\
		actions/gtk-go-down\
		actions/stock_down\
	actions/go-first\
		actions/gtk-goto-first-ltr\
		actions/gtk-goto-last-rtl\
		actions/start\
		actions/stock_first\
		actions/go-last-rtl\
	actions/go-last\
		actions/finish\
		actions/gtk-goto-first-rtl\
		actions/gtk-goto-last-ltr\
		actions/stock_last\
		actions/go-first-rtl\
	actions/go-next\
		actions/forward\
		actions/gtk-go-back-rtl\
		actions/gtk-go-forward-ltr\
		actions/next\
		actions/stock_right\
		actions/go-previous-rtl\
	actions/go-previous\
		actions/back\
		actions/gtk-go-back-ltr\
		actions/gtk-go-forward-rtl\
		actions/previous\
		actions/stock_left\
		actions/go-next-rtl\
	actions/go-top\
		actions/gtk-goto-top\
		actions/stock_top\
		actions/top\
	actions/go-up\
		actions/gtk-go-up\
		actions/stock_up\
		actions/up\
	actions/touchpad-disabled\
	actions/touchpad-enabled\
	actions/error-correct\
	actions/document-send\
	actions/send-to\
	actions/dnd-multiple\
		actions/gtk-dnd-multiple\
	actions/system-switch-user\
	actions/system-shutdown\
		actions/gnome-shutdown\
	actions/system-log-out\
		actions/gnome-logout\
	actions/system-lock-screen\
		actions/gnome-lockscreen\
		actions/lock\
		actions/xfce-system-lock\
	devices/ac-adapter\
	devices/audio-card\
		devices/yast_soundcard\
	devices/audio-headphones\
		devices/headphones\
	devices/audio-headset\
	devices/audio-input-microphone\
		devices/gnome-stock-mic\
		devices/stock_mic\
	devices/audio-speakers\
	devices/battery\
		devices/gnome-dev-battery\
	devices/camera-photo\
		devices/camera\
		devices/camera_unmount\
		devices/blueman-camera\
	devices/camera-video\
	devices/camera-web\
	devices/colorimeter-colorhug\
	devices/computer\
		devices/gnome-dev-computer\
		devices/gnome-fs-client\
		devices/system\
	devices/display-projector\
	devices/drive-multidisk\
	devices/drive-optical\
		devices/drive-cdrom\
		devices/gnome-dev-cdrom\
		devices/gnome-dev-dvd\
	devices/drive-removable-media\
		devices/gnome-dev-removable-1394\
		devices/gnome-dev-removable\
		devices/gnome-dev-removable-usb\
		devices/usbpendrive_unmount\
	devices/input-dialpad\
	devices/input-mouse\
		devices/gnome-dev-mouse-ball\
		devices/gnome-dev-mouse-optical\
		devices/mouse\
		devices/xfce4-mouse\
		devices/yast_mouse\
		devices/blueman-mouse\
		devices/blueman-pointing\
	devices/input-tablet\
		categories/preferences-desktop-peripherals\
			categories/input_devices_settings\
	devices/input-touchpad\
	devices/input-keyboard\
		devices/gnome-dev-keyboard\
		devices/keyboard\
		devices/kxkb\
		devices/xfce4-keyboard\
		devices/blueman-keyboard\
	devices/media-flash\
		devices/gnome-dev-media-cf\
		devices/gnome-dev-media-ms\
		devices/gnome-dev-media-sdmmc\
		devices/gnome-dev-media-sm\
	devices/media-floppy\
		devices/3floppy_unmount\
		devices/gnome-dev-floppy\
		devices/gtk-floppy\
		devices/media-zip\
		devices/system-floppy\
	devices/media-optical-cd-audio\
		devices/media-optical-audio\
		devices/media-cdrom-audio\
		devices/gnome-dev-cdrom-audio\
	devices/media-optical\
		devices/media-optical-cd\
			devices/media-optical-cdr\
				devices/media-optical-cd-r\
				devices/gnome-dev-disc-cdr\
			devices/media-optical-cdrw\
				devices/media-cdrw\
				devices/gnome-dev-disc-cdrw\
			devices/gtk-cdrom\
			devices/media-cdrom\
		devices/cdrom_unmount\
			devices/cdwriter_unmount\
			devices/dvd_unmount\
		devices/media-optical-bd\
		devices/media-optical-dvd\
			devices/media-dvd\
			devices/media-optical-dvd-ram\
				devices/gnome-dev-disc-dvdram\
			devices/media-optical-dvd-rom\
				devices/gnome-dev-disc-dvdrom\
			devices/media-optical-dvd-r\
				devices/gnome-dev-disc-dvdr\
				devices/media-optical-dvd-r-plus\
					devices/gnome-dev-disc-dvdr-plus\
			devices/media-optical-dvd-rw\
				devices/media-dvdrw\
				devices/gnome-dev-disc-dvdrw\
		mimetypes/application-x-cd-image\
	devices/media-removable\
	devices/media-tape\
	devices/modem\
		devices/gnome-modem\
		devices/modem-manager\
	devices/multimedia-player\
		devices/ipod\
			devices/gnome-dev-ipod\
			devices/ipod_mount\
		apps/gmtpicon\
	devices/network-wired\
		devices/gnome-dev-ethernet\
	devices/network-wireless\
		devices/gnome-dev-wavelan\
	devices/pda\
		apps/visor\
	devices/phone\
		devices/stock_cell-phone\
		devices/blueman-phone\
		devices/blueman-cellular\
		devices/phone-manager\
	devices/printer-network\
		devices/network-printer\
		devices/stock_network-printer\
	devices/printer\
		devices/gnome-dev-printer\
		devices/kjobviewer\
		devices/printer1\
		devices/printer-remote\
		devices/printmgr\
		devices/stock_printers\
		devices/xfce-printer\
		devices/yast_printer\
	devices/scanner\
		devices/blueman-scanner\
	devices/tv\
		mimetypes/application-x-pitivi\
		apps/tv-player\
	devices/uninterruptible-power-supply\
	devices/video-display\
		devices/chardevice\
		devices/display\
		devices/xfce4-display\
		devices/blueman-desktop\
	devices/thunderbolt\
	devices/video-joined-displays\
	devices/video-single-display\
	devices/computer-apple-ipad\
	devices/smartphone\
		devices/multimedia-player-apple-ipod-touch\
		devices/phone-apple-iphone\
		devices/phone-google-nexus-one\
		devices/phone-htc-g1-white\
		devices/phone-palm-pre\
		devices/phone-samsung-galaxy-s\
	devices/drive-harddisk\
		devices/gnome-dev-harddisk\
		devices/gtk-harddisk\
		devices/harddrive\
			devices/block-device\
		devices/hdd_unmount\
		devices/yast_HD\
		devices/yast_idetude\
		devices/drive-harddisk-system\
		devices/drive-harddisk-ieee1394\
			devices/gnome-dev-harddisk-1394\
		devices/drive-harddisk-usb\
			devices/gnome-dev-harddisk-usb\
	devices/drive-harddisk-solidstate\
		devices/drive-harddisk-system-solidstate\
		devices/drive-harddisk-ieee1394-solidstate\
		devices/drive-harddisk-usb-solidstate\
	places/user-home\
		places/folder_home\
		places/gnome-fs-home\
	places/folder-saved-search\
		places/application-x-gnome-saved-search\
	places/folder\
		places/gnome-fs-directory\
		places/stock_folder\
		places/inode-directory\
		places/gtk-directory\
		mimetypes/inode-directory\
	places/folder-remote\
		places/gnome-fs-ftp\
		places/gnome-fs-nfs\
		places/gnome-fs-share\
		places/gnome-fs-smb\
			places/gnome-mime-x-directory-smb-share\
		places/gnome-fs-ssh\
		places/network\
	places/folder-documents\
	places/folder-download\
	places/folder-music\
	places/folder-pictures\
	places/folder-publicshare\
	places/folder-templates\
	places/folder-videos\
	places/user-bookmarks\
	places/user-desktop\
		places/desktop\
		places/gnome-fs-desktop\
	places/user-trash\
		mimetypes/application-x-trash\
	places/emptytrash\
		places/gnome-fs-trash-empty\
		places/gnome-stock-trash\
		places/trashcan_empty\
		places/xfce-trash_empty\
	places/network-server\
		places/gnome-fs-server\
		places/gnome-mime-x-directory-nfs-server\
		places/gnome-mime-x-directory-smb-server\
		places/redhat-network-server\
		places/server\
	places/network-workgroup\
		places/gnome-fs-network\
		places/gnome-mime-x-directory-smb-workgroup\
		places/gtk-network\
		places/network_local\
	emotes/emote-love\
	emotes/face-angel\
		emotes/stock_smiley-18\
	emotes/face-angry\
	emotes/face-confused\
	emotes/face-cool\
		emotes/stock_smiley-15\
	emotes/face-crying\
		emotes/stock_smiley-11\
	emotes/face-devilish\
	emotes/face-glasses\
	emotes/face-laugh\
	emotes/face-yawn\
	emotes/face-shutmouth\
	emotes/face-sick\
	emotes/face-worried\
	emotes/face-uncertain\
	emotes/face-embarrassed\
	emotes/face-surprise\
		emotes/face-surprised\
		emotes/stock_smiley-5\
	emotes/face-smile\
		emotes/stock_smiley-1\
		emotes/stock_smiley-2\
		emotes/stock_smiley-7\
	emotes/face-wink\
		emotes/stock_smiley-3\
	emotes/face-sad\
		emotes/stock_smiley-4\
	emotes/face-monkey\
		emotes/stock_smiley-22\
	emotes/face-kiss\
		emotes/stock_smiley-13\
	emotes/face-smile-big\
		emotes/stock_smiley-6\
	emotes/face-smirk\
	emotes/face-plain\
		emotes/stock_smiley-8\
	emotes/face-raspberry\
		emotes/stock_smiley-10\
	emotes/face-tired\
	emblems/emblem-web\
	emblems/emblem-package\
	emblems/emblem-default\
	emblems/emblem-generic\
	emblems/emblem-new\
	emblems/emblem-documents\
	emblems/emblem-favorite\
	emblems/emblem-important\
	emblems/emblem-music\
	emblems/emblem-ok\
	emblems/emblem-photos\
	emblems/emblem-shared\
	emblems/emblem-synchronizing\
	emblems/emblem-system\
	emblems/emblem-videos\
	emblems/emblem-red\
	emblems/emblem-green\
	emblems/emblem-yellow\
	emblems/emblem-blue\
	emblems/emblem-magenta\
	emblems/emblem-cyan\
	emblems/emblem-note\
	emblems/emblem-urgent\
	emblems/emblem-mail\
	emblems/emblem-readonly\
		emblems/emblem-nowrite\
	emblems/emblem-unreadable\
		emblems/emblem-noread\
	emblems/emblem-games\
	emblems/emblem-downloads\
	emblems/emblem-symbolic-link\
	mimetypes/application-x-bittorrent\
	mimetypes/application-certificate\
		mimetypes/stock_certificate\
	mimetypes/application-rss+xml\
		apps/internet-feed-reader\
			apps/internet-news-reader\
			apps/liferea\
			apps/lottanzb\
			apps/greader\
			apps/news-feed\
			apps/pan\
			apps/rss\
	mimetypes/application-x-appliance\
	mimetypes/application-x-executable\
		mimetypes/binary\
		mimetypes/exec\
		mimetypes/gnome-fs-executable\
		mimetypes/gnome-mime-application-x-executable\
		mimetypes/gnome-mime-application-x-ms-dos-executable\
	mimetypes/audio-x-generic\
		mimetypes/gnome-mime-application-ogg\
		mimetypes/gnome-mime-audio\
		mimetypes/sound\
		mimetypes/audio\
		mimetypes/audio-mp3\
		mimetypes/audio-x-speex+org\
	mimetypes/image-x-generic\
		mimetypes/gnome-mime-application-x-killustrator\
		mimetypes/gnome-mime-image\
		mimetypes/image\
		mimetypes/image-x-eps\
	mimetypes/package-x-generic\
		mimetypes/deb\
		mimetypes/folder_tar\
		mimetypes/gnome-mime-application-x-7z-compressed\
		mimetypes/gnome-mime-application-x-archive\
		mimetypes/gnome-mime-application-x-arj\
		mimetypes/gnome-mime-application-x-bzip\
		mimetypes/gnome-mime-application-x-bzip-compressed-tar\
		mimetypes/gnome-mime-application-x-compress\
		mimetypes/gnome-mime-application-x-compressed-tar\
		mimetypes/gnome-mime-application-x-cpio\
		mimetypes/gnome-mime-application-x-cpio-compressed\
		mimetypes/gnome-mime-application-x-deb\
		mimetypes/gnome-mime-application-x-gzip\
		mimetypes/gnome-mime-application-x-jar\
			mimetypes/application-x-java-archive\
		mimetypes/gnome-mime-application-x-lha\
		mimetypes/gnome-mime-application-x-lhz\
		mimetypes/gnome-mime-application-x-lzma\
		mimetypes/gnome-mime-application-x-lzma-compressed-tar\
		mimetypes/gnome-mime-application-x-rar\
		mimetypes/rpm\
			mimetypes/gnome-mime-application-x-rpm\
		mimetypes/gnome-mime-application-x-stuffit\
		mimetypes/gnome-mime-application-x-tar\
		mimetypes/tar\
			mimetypes/gnome-mime-application-x-tarz\
		mimetypes/zip\
			mimetypes/gnome-mime-application-zip\
		mimetypes/gnome-package\
		mimetypes/package\
		mimetypes/tgz\
	mimetypes/text-x-generic\
		mimetypes/gtk-file\
			mimetypes/gnome-fs-regular\
		mimetypes/application-x-tex\
		mimetypes/ascii\
			mimetypes/mime_ascii\
		mimetypes/empty\
		mimetypes/gnome-mime-text\
		mimetypes/misc\
			mimetypes/unknown\
		mimetypes/package_editors\
		mimetypes/txt\
		mimetypes/txt2\
		mimetypes/libreoffice-master-document\
			mimetypes/libreoffice-oasis-master-document\
			apps/libreoffice-main\
				apps/libreoffice-startcenter\
		mimetypes/text-x-boo\
		mimetypes/text-x-changelog\
		mimetypes/text-x-copying\
		mimetypes/text-x-install\
		mimetypes/text-x-java\
		mimetypes/text-x-log\
		mimetypes/text-x-makefile\
		mimetypes/text-x-authors\
		mimetypes/text-xml\
		mimetypes/text-css\
		mimetypes/text-html\
			mimetypes/gnome-mime-application-vnd.oasis.opendocument.text-web\
			mimetypes/gnome-mime-application-xhtml+xml\
			mimetypes/gnome-mime-application-x-php\
			mimetypes/gnome-mime-text-html\
			mimetypes/gnome-mime-text-vnd.wap.wml\
			mimetypes/html\
			mimetypes/www\
		mimetypes/text-x-opml+xml\
		mimetypes/text-x-patch\
		mimetypes/text-x-readme\
		mimetypes/text-x-src\
			mimetypes/text-x-csharp\
			mimetypes/text-x-c++src\
				mimetypes/text-x-c++\
			mimetypes/text-x-csrc\
				mimetypes/text-x-c\
			mimetypes/text-x-hdr\
				mimetypes/text-x-c++hdr\
				mimetypes/text-x-chdr\
		mimetypes/text-x-apport\
		mimetypes/application-x-desktop\
		mimetypes/application-x-package-list\
		mimetypes/application-x-php\
		mimetypes/application-x-planner\
		mimetypes/text-x-script\
			mimetypes/application-x-javascript\
				mimetypes/text-x-javascript\
			mimetypes/application-x-ruby\
			mimetypes/application-x-perl\
				mimetypes/gnome-mime-application-x-perl\
			mimetypes/text-x-python\
				mimetypes/gnome-mime-text-x-python\
			mimetypes/gnome-mime-application-x-shellscript\
				mimetypes/gnome-mime-text-x-csh\
				mimetypes/gnome-mime-text-x-sh\
				mimetypes/gnome-mime-text-x-zsh\
				mimetypes/shellscript\
			mimetypes/stock_script\
		mimetypes/emacs-document\
			mimetypes/emacs-document23\
		mimetypes/application-x-mono-develop-xib\
	mimetypes/application-x-addon\
		mimetypes/extension\
		mimetypes/plugin\
			mimetypes/pluma-plugin\
	mimetypes/application-x-firmware\
		mimetypes/x-firmware\
	mimetypes/application-x-keepass\
		mimetypes/application-pgp-encrypted\
			mimetypes/multipart-encrypted\
	mimetypes/font-x-generic\
		mimetypes/font-bitmap\
			mimetypes/font_bitmap\
			mimetypes/gnome-mime-application-x-font-bdf\
			mimetypes/gnome-mime-application-x-font-linux-psf\
			mimetypes/gnome-mime-application-x-font-pcf\
		mimetypes/font\
		mimetypes/font_truetype\
		mimetypes/font_type1\
		mimetypes/gnome-mime-application-x-font-afm\
			mimetypes/gnome-mime-x-font-afm\
		mimetypes/gnome-mime-application-x-font-sunos-news\
		mimetypes/gnome-mime-application-x-font-ttf\
	mimetypes/x-office-extension\
		mimetypes/libreoffice-extension\
		mimetypes/application-vnd.openofficeorg.extension\
			mimetypes/openofficeorg3-extension\
			mimetypes/openofficeorg-extension\
	mimetypes/video-x-generic\
		mimetypes/gnome-mime-application-vnd.rn-realmedia\
		mimetypes/gnome-mime-application-vnd.rn-realmedia-secure\
		mimetypes/gnome-mime-application-vnd.rn-realmedia-vbr\
		mimetypes/gnome-mime-application-x-shockwave-flash\
		mimetypes/gnome-mime-video\
		mimetypes/video\
	mimetypes/x-office-address-book\
		mimetypes/contents2\
		mimetypes/stock_addressbook\
		mimetypes/vcard\
			mimetypes/gnome-mime-text-x-vcard\
	mimetypes/x-office-calendar\
		mimetypes/vcalendar\
			mimetypes/gnome-mime-text-x-vcalendar\
		mimetypes/plan\
		mimetypes/stock_calendar\
	mimetypes/x-office-database\
		apps/libreoffice-base\
		mimetypes/libreoffice-database\
		mimetypes/libreoffice-oasis-database\
		mimetypes/openofficeorg23-database\
	mimetypes/x-office-document\
		apps/libreoffice-writer\
		mimetypes/application-vnd.ms-word.document.macroEnabled.12\
		mimetypes/application-vnd.openxmlformats-officedocument.wordprocessingml.document\
		mimetypes/document\
		mimetypes/gnome-mime-application-msword\
		mimetypes/gnome-mime-application-postscript\
		mimetypes/gnome-mime-application-rtf\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.text\
		mimetypes/gnome-mime-application-vnd.stardivision.writer\
		mimetypes/gnome-mime-application-vnd.sun.xml.writer\
		mimetypes/gnome-mime-application-wordperfect\
		mimetypes/gnome-mime-application-x-abiword\
		mimetypes/gnome-mime-application-x-applix-word\
		mimetypes/gnome-mime-application-x-dvi\
		mimetypes/gnome-mime-application-x-gzpostscript\
		mimetypes/gnome-mime-application-x-kword\
		mimetypes/gnome-mime-application-x-scribus\
		mimetypes/gnome-mime-application-x-tex\
		mimetypes/libreoffice-oasis-text\
		mimetypes/libreoffice-text\
		mimetypes/openofficeorg3-oasis-text\
		mimetypes/openofficeorg3-text\
		mimetypes/openofficeorg-oasis-text\
		mimetypes/openofficeorg-text\
		mimetypes/package_wordprocessing\
		mimetypes/wordprocessing\
	mimetypes/x-office-drawing\
		apps/libreoffice-draw\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.graphics\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.image\
		mimetypes/gnome-mime-application-vnd.sun.xml.draw\
		mimetypes/libreoffice-drawing\
		mimetypes/libreoffice-oasis-drawing\
		mimetypes/openofficeorg3-drawing\
		mimetypes/openofficeorg3-oasis-drawing\
		mimetypes/openofficeorg-drawing\
		mimetypes/openofficeorg-oasis-drawing\
	mimetypes/x-office-presentation\
		apps/libreoffice-impress\
		mimetypes/application-vnd.ms-powerpoint.presentation.macroEnabled.12\
		mimetypes/application-vnd.openxmlformats-officedocument.presentationml.presentation\
		mimetypes/gnome-mime-application-magicpoint\
		mimetypes/gnome-mime-application-vnd.ms-powerpoint\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.presentation\
		mimetypes/gnome-mime-application-vnd.stardivision.impress\
		mimetypes/gnome-mime-application-vnd.sun.xml.impress\
		mimetypes/gnome-mime-application-x-kpresenter\
		mimetypes/kpresenter_kpr\
			apps/kpresenter\
		mimetypes/libreoffice-oasis-presentation\
		mimetypes/libreoffice-presentation\
		mimetypes/openofficeorg3-oasis-presentation\
		mimetypes/openofficeorg3-presentation\
		mimetypes/openofficeorg-oasis-presentation\
		mimetypes/openofficeorg-presentation\
	mimetypes/x-office-spreadsheet\
		apps/libreoffice-calc\
			apps/openofficeorg-calc\
		mimetypes/openofficeorg-spreadsheet\
		mimetypes/application-vnd.ms-excel.sheet.macroEnabled.12\
		mimetypes/application-vnd.openxmlformats-officedocument.spreadsheetml.sheet\
		mimetypes/gnome-mime-application-vnd.lotus-1-2-3\
		mimetypes/gnome-mime-application-vnd.ms-excel\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.spreadsheet\
		mimetypes/gnome-mime-application-vnd.stardivision.calc\
		mimetypes/gnome-mime-application-vnd.sun.xml.calc\
		mimetypes/gnome-mime-application-x-applix-spreadsheet\
		mimetypes/gnome-mime-application-x-gnumeric\
		mimetypes/gnome-mime-application-x-kspread\
		mimetypes/libreoffice-oasis-spreadsheet\
		mimetypes/libreoffice-spreadsheet\
		mimetypes/openofficeorg3-oasis-spreadsheet\
		mimetypes/openofficeorg3-spreadsheet\
		mimetypes/openofficeorg-oasis-spreadsheet\
		mimetypes/openofficeorg-spreadsheet\
		mimetypes/spreadsheet\
		mimetypes/text-csv\
	mimetypes/application-pdf\
		mimetypes/gnome-mime-application-pdf\
		mimetypes/pdf\
		apps/atril\
			apps/xpdf\
			apps/gnome-pdf\
			apps/evince\
	mimetypes/text-x-generic-template\
		mimetypes/template_source\
	mimetypes/x-office-document-template\
		mimetypes/application-vnd.openxmlformats-officedocument.wordprocessingml.template\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.text-template\
		mimetypes/gnome-mime-application-vnd.sun.xml.writer.template\
		mimetypes/libreoffice-oasis-text-template\
		mimetypes/libreoffice-text-template\
		mimetypes/openofficeorg3-oasis-text-template\
		mimetypes/openofficeorg3-text-template\
		mimetypes/openofficeorg-oasis-text-template\
		mimetypes/openofficeorg-text-template\
	mimetypes/x-office-drawing-template\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.graphics-template\
		mimetypes/gnome-mime-application-vnd.sun.xml.draw.template\
		mimetypes/libreoffice-drawing-template\
		mimetypes/libreoffice-oasis-drawing-template\
		mimetypes/openofficeorg3-drawing-template\
		mimetypes/openofficeorg3-oasis-drawing-template\
		mimetypes/openofficeorg-drawing-template\
		mimetypes/openofficeorg-oasis-drawing-template\
	mimetypes/x-office-formula\
		mimetypes/libreoffice-formula\
		mimetypes/libreoffice-oasis-formula\
		apps/libreoffice-math\
	mimetypes/x-office-formula-template\
	mimetypes/x-office-spreadsheet-template\
		mimetypes/application-vnd.openxmlformats-officedocument.spreadsheetml.template\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.spreadsheet-template\
		mimetypes/gnome-mime-application-vnd.sun.xml.calc.template\
		mimetypes/libreoffice-oasis-spreadsheet-template\
		mimetypes/libreoffice-spreadsheet-template\
		mimetypes/openofficeorg3-oasis-spreadsheet-template\
		mimetypes/openofficeorg3-spreadsheet-template\
		mimetypes/openofficeorg-oasis-spreadsheet-template\
		mimetypes/openofficeorg-spreadsheet-template\
	mimetypes/x-office-presentation-template\
		mimetypes/gnome-mime-application-vnd.oasis.opendocument.presentation-template\
		mimetypes/gnome-mime-application-vnd.sun.xml.impress.template\
		mimetypes/application-vnd.openxmlformats-officedocument.presentationml.template\
		mimetypes/openofficeorg3-presentation-template\
		mimetypes/openofficeorg3-oasis-presentation-template\
		mimetypes/libreoffice-presentation-template\
		mimetypes/libreoffice-oasis-presentation-template\
		mimetypes/openofficeorg-presentation-template\
		mimetypes/openofficeorg-oasis-presentation-template

#actions/mail-message-new
#	actions/mail_new
#	actions/stock_mail-compose
#	actions/gnome-stock-mail-new

#actions/mail-mark-junk
#	actions/mail_spam
#	actions/stock_spam

#apps/mozo
#	apps/alacarte


ALL_PNG_ICONS = $(foreach S,$(SIZES),$(foreach I,$(ICONS),$(S)x$(S)/$(I).png))

all: simple.theme $(ALL_PNG_ICONS)

simple.theme: Makefile
	set -e;\
	printf '%s\n' \
		'[Icon Theme]'\
		'Name=Simple'\
		'Comment=A very simple icon theme'\
		'Example=folder'\
		''\
		'# KDE specific stuff'\
		'DisplayDepth=32'\
		'LinkOverlay=link_overlay'\
		'LockOverlay=lock_overlay'\
		'ZipOverlay=zip_overlay'\
		'DesktopDefault=48'\
		'DesktopSizes='$$(printf ',%s' $(SIZES) | sed 's/^,//')\
		'ToolbarDefault=22'\
		'ToolbarSizes=8,16,22,32,48'\
		'MainToolbarDefault=22'\
		'MainToolbarSizes=8,16,22,32,48'\
		'SmallDefault=16'\
		'SmallSizes=16'\
		'PanelDefault=32'\
		'PanelSizes='$$(printf ',%s' $(SIZES) | sed 's/^,//')\
		''\
		> simple.theme
	printf 'Directories=' >> simple.theme
	set -e;\
	for s in $(SIZES); do\
		for d in $(DIRS); do\
			printf ',%sx%s/%s' $$s $$s $$d;\
		done;\
	done | sed 's/^,//' >> simple.theme
	set -e;\
	for d in $(DIRS); do\
		printf ',scalable/%s' $$d;\
	done | sed 's/^,//' >> simple.theme
	printf '\n' >> simple.theme
	set -e;\
	for s in $(SIZES) scalable; do\
		for d in $(DIRS); do\
			printf '\n';\
			./make-dir-info $$s $$d;\
		done;\
	done >> simple.theme

8x8/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

16x16/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

22x22/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

24x24/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

32x32/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

36x36/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

48x48/%.png: scalable/%.svg
	mkdir -p -- $(@D)
	s="$$(printf '%s\n' $@ | cut -d x -f 1)";\
	if test -L $<; then\
		ln -sf "$$(readlink $< | sed 's/\.svg$$/\.png/')" $@;\
	else\
		rsvg-convert -w $$s -h $$s -f png $< > $@;\
	fi

install: simple.theme $(ALL_PNG_ICONS)
	mkdir -p -- "$(DESTDIR)$(ICONPREFIX)"
	sed -e;\
	for d in $(DIRS); do\
		for s in $(SIZES); do\
			mkdir -p -- "$(DESTDIR)$(ICONPREFIX)/simple/$${s}x$${s}/$${d}";\
		done;\
		mkdir -p -- "$(DESTDIR)$(ICONPREFIX)/simple/scalable/$${d}";\
	done
	set -e;\
	for i in $(ICONS); do\
		for s in $(SIZES); do\
			cp -- "$${s}x$${s}/$${i}.png" "$(DESTDIR)$(ICONPREFIX)/simple/$${s}x$${s}/$${i}.png";\
		done;\
		cp -- "scalable/$${i}.svg" "$(DESTDIR)$(ICONPREFIX)/simple/scalable/$${i}.svg";\
	done
	cp -- simple.theme "$(DESTDIR)$(ICONPREFIX)/simple/simple.theme"

uninstall:
	rm -rf -- "$(DESTDIR)$(ICONPREFIX)/simple"

clean:
	-rm -f -- simple.theme
	-rm -f -- $(foreach S,$(SIZES),$(foreach I,$(ICONS),$(S)x$(S)/$(I).png))
	-rmdir -- $(foreach S,$(SIZES),$(foreach D,$(DIRS),$(S)x$(S)/$(D)) $(S)x$(S))

.PHONY: all install uninstall clean
