#!/bin/sh

if test "$2" = actions; then
	context=Actions
elif test "$2" = animations; then
	context=Animations
elif test "$2" = categories; then
	context=Categories
elif test "$2" = devices; then
	context=Devices
elif test "$2" = emblems; then
	context=Emblems
elif test "$2" = emotes; then
	context=Emotes
elif test "$2" = mimetypes; then
	context=MimeTypes
elif test "$2" = places; then
	context=Places
elif test "$2" = status; then
	context=Status
fi

if test "$1" = scalable; then
	printf '[%s/%s]\n' "$1" "$2"
	printf '%s\n' Context="$context" Size="16" MinSize="8" MaxSize="1024" Type="Scalable"
else
	printf '[%sx%s/%s]\n' "$1" "$1" "$2"
	printf '%s\n' Context="$context" Size="$1" Type="Fixed"
fi
